### Dataset: Iowa Liquor Sales (Sales & Distribution)
https://data.iowa.gov/Sales-Distribution/Iowa-Liquor-Sales/m3tr-qhgy

##### Updated
##### April 1, 2021
##### Data Provided by
##### Iowa Department of Commerce, Alcoholic Beverages Division

### What's in this Dataset?
Rows
21M

Columns
24

Each row is a
individual product purchase

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_json('https://data.iowa.gov/resource/m3tr-qhgy.json')
df

,invoice_line_no,date,store,name,address,city,zipcode,county_number,county,category,...,sale_bottles,sale_dollars,sale_liters,sale_gallons,store_location,:@computed_region_3r5t_5243,:@computed_region_wnea_7qqw,:@computed_region_i9mz_6gmt,:@computed_region_uhgg_e8y2,:@computed_region_e7ym_nrbf
0,S31296100034,2016-03-16,3762,Wine and Spirits Gallery,7690 HICKMAN RD,WINDSOR HEIGHTS,50322.0,77.0,Polk,1081200,...,1,10.85,1.00,0.26,NaN,NaN,NaN,NaN,NaN,NaN
1,INV-20599500022,2019-07-15,4320,Fareway Stores #470 / Perry,NaN,NaN,NaN,NaN,NaN,1012200,...,6,94.50,10.50,2.77,NaN,NaN,NaN,NaN,NaN,NaN
2,INV-28403900139,2020-07-01,2643,Hy-Vee Wine and Spirits / Waterloo,2126 Kimball Ave,Waterloo,50701.0,7.0,BLACK HAWK,1012400,...,2,97.44,3.50,0.92,NaN,NaN,NaN,NaN,NaN,NaN
3,INV-20560900100,2019-07-11,3456,Quick Shop / Clear Lake,NaN,NaN,NaN,NaN,NaN,1012200,...,2,20.22,2.00,0.52,NaN,NaN,NaN,NaN,NaN,NaN
4,INV-20784900043,2019-07-23,5151,IDA Liquor,"500, Hwy 175",Ida Grove,51445.0,47.0,IDA,1701100,...,6,162.00,11.10,2.93,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,INV-28766900073,2020-07-16,5142,Smokin' Joe's #13 Tobacco and Liquor Outlet,2315 Mt Vernon Rd SE,Cedar Rapids,52303.0,57.0,Linn,1062100,...,3,19.89,3.00,0.79,NaN,NaN,NaN,NaN,NaN,NaN
996,INV-20337700022,2019-07-01,3882,Kwik Shop #579 / Davenport,2805 Telegraph Rd,Davenport,52802.0,82.0,SCOTT,1062400,...,10,41.10,3.75,0.99,NaN,NaN,NaN,NaN,NaN,NaN
997,INV-25356900010,2020-02-20,5135,Fareway Stores #155 / Huxley,911 Hwy 69,Huxley,50124.0,85.0,STORY,1062500,...,12,134.88,9.00,2.37,NaN,NaN,NaN,NaN,NaN,NaN
998,INV-20490700100,2019-07-09,2666,Hy-Vee Food Store #2 / State Ankeny,NaN,NaN,NaN,NaN,NaN,1062400,...,2,8.22,0.75,0.19,NaN,NaN,NaN,NaN,NaN,NaN
999,INV-20339300007,2019-07-01,5336,Express Mart,4804 S Highway 61,Muscatine,52761.0,70.0,MUSCATINE,1062400,...,12,104.04,9.00,2.37,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
df1 = pd.read_json('https://data.iowa.gov/resource/m3tr-qhgy.json?invoice_line_no=306831300002')
df1

,invoice_line_no,date,store,name,address,city,zipcode,store_location,county_number,county,...,itemno,im_desc,pack,bottle_volume_ml,state_bottle_cost,state_bottle_retail,sale_bottles,sale_dollars,sale_liters,sale_gallons
0,306831300002,2012-07-30,3869,Bootleggin' Barzini's Fin,412 1ST AVE,CORALVILLE,52241,"{'type': 'Point', 'coordinates': [-91.565517, ...",52,Johnson,...,35934,Grey Goose Cherry Noir,6,750,17.97,26.96,2,53.92,1.5,0.4

In [10]:
zipcode = pd.read_json('https://data.iowa.gov/resource/m3tr-qhgy.json?zipcode=50322')
zipcode

,invoice_line_no,date,store,name,address,city,zipcode,county_number,county,category,...,im_desc,pack,bottle_volume_ml,state_bottle_cost,state_bottle_retail,sale_bottles,sale_dollars,sale_liters,sale_gallons,store_location
0,S31296100034,2016-03-16,3762,Wine and Spirits Gallery,7690 HICKMAN RD,WINDSOR HEIGHTS,50322,77,Polk,1081200,...,Ryan's Cream Liqueur,12,1000,7.23,10.85,1,10.85,1.00,0.26,NaN
1,INV-20490100021,2019-07-09,2663,Hy-Vee Food Store / Urbandale,8701 Douglas,Urbandale,50322,77,POLK,1012200,...,Usher's Green Stripe,6,1750,10.00,15.00,6,90.00,10.50,2.77,"{'type': 'Point', 'coordinates': [-93.739105, ..."
2,INV-31692100005,2020-11-05,3877,Target Store T-2041 / Des Moines,5901 Douglas Ave,Des Moines,50322,77,Polk,1012200,...,Lauders,6,1750,11.18,16.77,6,87.78,10.50,2.77,"{'type': 'Point', 'coordinates': [-93.699209, ..."
3,INV-28533700076,2020-07-07,2663,Hy-Vee Food Store / Urbandale,8701 Douglas,Urbandale,50322,77,POLK,1032100,...,Pinnacle,12,750,6.50,9.75,12,117.00,9.00,2.37,"{'type': 'Point', 'coordinates': [-93.739105, ..."
4,S31540000071,2016-03-30,3762,Wine and Spirits Gallery,7690 HICKMAN RD,WINDSOR HEIGHTS,50322,77,Polk,1032200,...,Stolichnaya Vanil Vodka 75 Proof,12,1000,15.97,23.96,1,23.96,1.00,0.26,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,INV-20428600037,2019-07-05,3691,Target Store T-1791 / Urbandale,11148 Plum Dr,Urbandale,50322,77,POLK,1011600,...,Templeton 6YR Rye,6,750,22.75,34.13,6,204.78,4.50,1.18,"{'type': 'Point', 'coordinates': [-93.769776, ..."
996,INV-20631900020,2019-07-16,4131,Fareway Stores #933 / Urbandale,8450 Meredith Dr,Urbandale,50322,77,POLK,1011200,...,Old Forester Bourbon 86prf,12,750,10.92,16.38,3,49.14,2.25,0.59,"{'type': 'Point', 'coordinates': [-93.734312, ..."
997,INV-20414300019,2019-07-05,4941,Kum & Go #170 / Urbandale,6990 Douglas Ave,Urbandale,50322,77,POLK,1041100,...,Seagrams Extra Dry Gin Mini,12,500,3.30,4.95,2,9.90,1.00,0.26,"{'type': 'Point', 'coordinates': [-93.711902, ..."
998,INV-20428600043,2019-07-05,3691,Target Store T-1791 / Urbandale,11148 Plum Dr,Urbandale,50322,77,POLK,1011600,...,Cedar Ridge Malted Rye,6,750,19.67,29.51,6,177.06,4.50,1.18,"{'type': 'Point', 'coordinates': [-93.769776, ..."
999,INV-20567100012,2019-07-12,5782,Casey's General Store #3606,5150 100th Street,Urbandale,50322,77,POLK,1011400,...,Jack Daniels Old #7 Black Label Flat,24,375,7.50,11.25,24,270.00,9.00,2.37,NaN

In [ ]:
df.info()

In [ ]:
chunksize = 10 ** 6
with pd.read_csv('Iowa_Liquor_Sales.csv', chunksize=chunksize) as reader:
    for chunk in reader:
#         print(chunk)
chunk

In [1]:
# filename = 'Iowa_Liquor_Sales.csv'
# chunksize = 1000000
# with pd.read_csv(filename, chunksize=chunksize) as reader:
#     for chunk in reader:
#         print(chunk)

In [19]:
import pandas as pd
line = 0
chksz = 1000000
for chunk in pd.read_csv("Iowa_Liquor_Sales.csv",chunksize = chksz):#,index_col=0):
    line += chunk.shape[0]
line

C:\Users\J\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3063: DtypeWarning: Columns (6) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
C:\Users\J\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3063: DtypeWarning: Columns (6,14) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

20965997

In [16]:
df = pd.read_csv(filename, skiprows = line - 1000)
df

,INV-35477100025,03/31/2021,3917,Smokin' Joe's #2 Tobacco and Liquor Outlet,1606 W Locust St,Davenport,52804,POINT (-90.599037 41.538254),82,SCOTT,...,11788,Black Velvet,6,1750,10.45,15.68,6.1,94.08,10.50,2.77
0,INV-35477600020,03/31/2021,5029,The Liquor Stop LLC,"211, W 53rd St",Davenport,52806,POINT (-90.57611300000002 41.574536),82,SCOTT,...,36969,New Amsterdam 80prf,12,750,7.50,11.25,12,135.00,9.00,2.37
1,INV-35476600002,03/31/2021,5371,State Food Mart,3715 State St.,Bettendorf,52722,POINT (-90.482018 41.528972),82,SCOTT,...,10804,Crown Royal Regal Apple,44,200,4.72,7.08,44,311.52,8.80,2.32
2,INV-35471700011,03/31/2021,2653,Hy-Vee Wine and Spirits / Washington,1004 W Madison St,Washington,52353,POINT (-91.704567 41.296576),92,WASHINGTON,...,64870,Fireball Cinnamon Whiskey,48,100,0.90,1.35,192,259.20,19.20,5.07
3,INV-35476600008,03/31/2021,5371,State Food Mart,3715 State St.,Bettendorf,52722,POINT (-90.482018 41.528972),82,SCOTT,...,38006,Smirnoff 80prf PET,12,750,8.25,12.38,12,148.56,9.00,2.37
4,INV-35480500072,03/31/2021,3420,Sam's Club 6344 / Windsor Heights,1101 73rd St,Windsor Heights,50311,POINT (-93.718027 41.599172),77,Polk,...,46504,Kraken Black Spiced Rum,12,750,10.45,15.68,12,188.16,9.00,2.37
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,INV-35472700003,03/31/2021,2601,Hy-Vee Food Store / Fairfield,1300 West Burlington Ave,Fairfield,52556,POINT (-91.978702 41.006456),51,JEFFERSON,...,57181,Chi-Chi''s Pineapple Margarita,6,1750,6.50,9.75,30,247.50,52.50,13.86
996,INV-35474700004,03/31/2021,2191,Keokuk Spirits,1013 Main,Keokuk,52632,POINT (-91.387797 40.400038),56,LEE,...,25607,Seagrams 7 Crown,12,1000,8.00,12.00,12,144.00,12.00,3.17
997,INV-35479400087,03/31/2021,2605,Hy-Vee Drugstore #5 / Cedar Rapids,2001 Blairs Ferry Road NE,Cedar Rapids,52402,POINT (-91.668919 42.034799),57,LINN,...,69634,Dr McGillicuddys Cherry,24,375,5.33,8.00,6,48.00,2.25,0.59
998,INV-35471400006,03/31/2021,4315,Fareway Stores #554 / Washington,301 North Marion Ave,Washington,52353,POINT (-91.692985 41.301967),92,WASHINGTON,...,18352,Four Roses Bourbon,12,750,12.50,18.75,12,213.12,9.00,2.37
999,INV-35476900009,03/31/2021,5559,W-Mart,1205 & 1207 E Locust St,Davenport,52803,POINT (-90.55792100000001 41.5383),82,SCOTT,...,32232,Seagrams Extra Dry Gin,48,100,0.97,1.46,48,70.08,4.80,1.26